### ISSUE TITLE
Project Prototyping

### ISSUE THREAD

**Issue by conorshortt123** [conorshortt123/facial-recognition-project#3]
Start coding a prototype of the project using flask/python.

To do:
- Frontend (Flask website)
- API (Python scripts)
- Backend (Database)

**Comment by BurkeBlaine1999** [comment]
Started researching how we can use PyMongo to connect a flask app to a MongoDB server.
Link to a youtube tutorial 
'https://www.youtube.com/watch?time_continue=155&v=3ZS7LEH_XBg&feature=emb_title'

**Comment by MarkReillyGMIT** [comment]
Added prototype of Flask website

**Comment by conorshortt123** [comment]
Basic prototype has been completed. We can now continue adding on to this prototype until we have a finished product.

- Flask frontend, has work to be done.
- Facial recognition API partially integrated with Flask.
- Backend MongoDB partially integrated with Flask.
