### ISSUE TITLE
Connecting Frontend to Backend database

### ISSUE THREAD

**Issue by MarkReillyGMIT** [conorshortt123/facial-recognition-project#4]

**Comment by BurkeBlaine1999** [comment]
Integrated MongoDB server into flask frontend

**Comment by BurkeBlaine1999** [comment]
Added registration authentication between flask app and MongoDB server

**Comment by BurkeBlaine1999** [comment]
Receiving data from server on the home page when searching for a user. Need tofix the image displaying

**Comment by conorshortt123** [comment]
Frontend and backend adequately connected.
