### ISSUE TITLE
Add video link

### ISSUE THREAD

**Issue by john-french** [conorshortt123/facial-recognition-project#7]
It would be more typical to have the video link included in the README markdown document [like this](https://web.microsoftstream.com/video/694637d7-c89a-4c9c-ab69-b054c5e34480?list=studio).

Checkout the markdown syntax for links ```[link text](url)```

**Comment by conorshortt123** [comment]
Will I update the readme in that case?

**Comment by john-french** [comment]
You can do if you like, not critical, just letting you know for the future. 
Might be no harm anyway.

**Comment by conorshortt123** [comment]
We won't be deducted marks or anything for updating after the due date? Cool thanks for letting us know John.

**Comment by john-french** [comment]
No, no deduction
